In [35]:
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sent = SentimentIntensityAnalyzer()
df = pd.read_csv('sample30.csv', usecols = ['reviews_text','id','brand','categories','manufacturer','name','reviews_date','reviews_didPurchase','reviews_doRecommend','reviews_rating','reviews_text','reviews_title','reviews_userCity','reviews_userProvince','reviews_username','user_sentiment'])
polarity = [round(sent.polarity_scores(i)['compound'], 2) for i in df['reviews_text']]
df['sentiment_score'] = polarity
df

id            brand  \
0      AV13O1A8GV-KLJ3akUyj  Universal Music   
1      AV14LG0R-jtxr-f38QfS         Lundberg   
2      AV14LG0R-jtxr-f38QfS         Lundberg   
3      AV16khLE-jtxr-f38VFn              K-Y   
4      AV16khLE-jtxr-f38VFn              K-Y   
...                     ...              ...   
29995  AVpfW8y_LJeJML437ySW    L'oreal Paris   
29996  AVpfW8y_LJeJML437ySW    L'oreal Paris   
29997  AVpfW8y_LJeJML437ySW    L'oreal Paris   
29998  AVpfW8y_LJeJML437ySW    L'oreal Paris   
29999  AVpfW8y_LJeJML437ySW    L'oreal Paris   

                                              categories  \
0      Movies, Music & Books,Music,R&b,Movies & TV,Mo...   
1      Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
2      Food,Packaged Foods,Snacks,Crackers,Snacks, Co...   
3      Personal Care,Medicine Cabinet,Lubricant/Sperm...   
4      Personal Care,Medicine Cabinet,Lubricant/Sperm...   
...                                                  ...   
29995  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   
29996  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   
29997  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   
29998  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   
29999  Beauty,Hair Care,Shampoo & Conditioner,Holiday...   

                             manufacturer  \
0      Universal Music Group / Cash Money   
1                                Lundberg   
2                                Lundberg   
3                                     K-Y   
4                                     K-Y   
...                                   ...   
29995                       L'oreal Paris   
29996                       L'oreal Paris   
29997                       L'oreal Paris   
29998                       L'oreal Paris   
29999                       L'oreal Paris   

                                                    name  \
0              Pink Friday: Roman Reloaded Re-Up (w/dvd)   
1             Lundberg Organic Cinnamon Toast Rice Cakes   
2             Lundberg Organic Cinnamon Toast Rice Cakes   
3                       K-Y Love Sensuality Pleasure Gel   
4                       K-Y Love Sensuality Pleasure Gel   
...                                                  ...   
29995  L'or233al Paris Elvive Extraordinary Clay Reba...   
29996  L'or233al Paris Elvive Extraordinary Clay Reba...   
29997  L'or233al Paris Elvive Extraordinary Clay Reba...   
29998  L'or233al Paris Elvive Extraordinary Clay Reba...   
29999  L'or233al Paris Elvive Extraordinary Clay Reba...   

                   reviews_date reviews_didPurchase reviews_doRecommend  \
0      2012-11-30T06:21:45.000Z                 NaN                 NaN   
1      2017-07-09T00:00:00.000Z                True                 NaN   
2      2017-07-09T00:00:00.000Z                True                 NaN   
3      2016-01-06T00:00:00.000Z               False               False   
4      2016-12-21T00:00:00.000Z               False               False   
...                         ...                 ...                 ...   
29995  2017-01-23T00:00:00.000Z               False                True   
29996  2017-01-27T00:00:00.000Z               False                True   
29997  2017-01-21T00:00:00.000Z               False                True   
29998  2017-01-11T00:00:00.000Z               False                True   
29999  2017-01-19T00:00:00.000Z               False                True   

       reviews_rating                                       reviews_text  \
0                   5  i love this album. it's very good. more to the...   
1                   5  Good flavor. This review was collected as part...   
2                   5                                       Good flavor.   
3                   1  I read through the reviews on here before look...   
4                   1  My husband bought this gel for us. The gel cau...   
...               ...                                                ...   
29995               5  I got thi

In [143]:
df_reco = df[["id", "name", "reviews_rating", "reviews_username"]]

In [144]:
df_reco.head()

id                                        name  \
0  AV13O1A8GV-KLJ3akUyj   Pink Friday: Roman Reloaded Re-Up (w/dvd)   
1  AV14LG0R-jtxr-f38QfS  Lundberg Organic Cinnamon Toast Rice Cakes   
2  AV14LG0R-jtxr-f38QfS  Lundberg Organic Cinnamon Toast Rice Cakes   
3  AV16khLE-jtxr-f38VFn            K-Y Love Sensuality Pleasure Gel   
4  AV16khLE-jtxr-f38VFn            K-Y Love Sensuality Pleasure Gel   

   reviews_rating reviews_username  
0               5           joshua  
1               5        dorothy w  
2               5        dorothy w  
3               1          rebecca  
4               1        walker557

In [145]:
null_count = df_reco[df_reco.columns[df_reco.isna().any()]].isna().sum().sort_values(ascending=False)
null_perc = (df_reco[df_reco.columns[df_reco.isna().any()]].isna().sum() * 100 / df_reco.shape[0]).sort_values(ascending=False)
null_data = pd.concat([null_count, null_perc], axis=1, keys=['Count', 'Percentage'])
null_data

Count  Percentage
reviews_username     63        0.21

In [146]:
df_reco = df_reco[~ df_reco.reviews_username.isna() ]

In [147]:
null_count = df_reco[df_reco.columns[df_reco.isna().any()]].isna().sum().sort_values(ascending=False)
null_perc = (df_reco[df_reco.columns[df_reco.isna().any()]].isna().sum() * 100 / df_reco.shape[0]).sort_values(ascending=False)
null_data = pd.concat([null_count, null_perc], axis=1, keys=['Count', 'Percentage'])
null_data

Empty DataFrame
Columns: [Count, Percentage]
Index: []

In [148]:
from sklearn.model_selection import train_test_split, cross_val_score

In [149]:
train, test = train_test_split(df_reco, test_size=0.30, random_state=42)

In [150]:
train.head(2)

id  \
962    AV1YGDqsGV-KLJ3adc-O   
10463  AVpf3VOfilAPnD_xjpun   

                                                    name  reviews_rating  \
962    Windex Original Glass Cleaner Refill 67.6oz (2...               5   
10463  Clorox Disinfecting Wipes Value Pack Scented 1...               5   

      reviews_username  
962         brittney w  
10463          cjshrad

In [151]:
df_pivot = train.pivot_table(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(0)

df_pivot.head(3)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            0.0                   0.0  ...   
01impala                           0.0                   0.0  ...   
02dakota                           0.0                   0.0  ...   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AVpfsQoeilAPnD_xgfx5  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   

id                AVpfv4TlilAPnD_xhjNS  AVpfvieo1cnluZ0-qdnu  
reviews_username                                              
00sab00                            0.0                   0.0  
01impala                           0.0                   0.0  
02dakota                           0.0                   0.0  

[3 rows x 256 columns]

In [152]:
dummy_train = train.copy()

In [153]:
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [154]:
dummy_train = dummy_train.pivot_table(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(1)

dummy_train.head(3)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            1.0                   1.0  ...   
01impala                           1.0                   1.0  ...   
02dakota                           1.0                   1.0  ...   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AVpfsQoeilAPnD_xgfx5  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02dakota                           1.0                   1.0   

id                AVpfv4TlilAPnD_xhjNS  AVpfvieo1cnluZ0-qdnu  
reviews_username                                              
00sab00                            1.0                   1.0  
01impala                           1.0                   1.0  
02dakota                           1.0                   1.0  

[3 rows x 256 columns]

In [155]:
dummy_train.shape

(18275, 256)

In [156]:
df_pivot = train.pivot_table(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
)

In [157]:
df_pivot[~df_pivot['AV13O1A8GV-KLJ3akUyj'].isna()]

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
joshua                             5.0                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
joshua                             NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
joshua                             NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
joshua                             NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
joshua                             NaN                   NaN  ...   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
joshua                             NaN                   NaN   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
joshua                             NaN                   NaN   

id                AVpfsQoeilAPnD_xgfx5  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
joshua                             NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
joshua                             NaN                   NaN   

id                AVpfv4TlilAPnD_xhjNS  AVpfvieo1cnluZ0-qdnu  
reviews_username                                              
joshua                             NaN                   NaN  

[1 rows x 256 columns]

In [158]:
import numpy as np

In [159]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [160]:
df_subtracted.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
0325home                           NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
02dakota                           NaN                   NaN  ...   
02deuce                            NaN                   NaN  ...   
0325home                           NaN                   NaN  ...   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfsQoeilAPnD_xgfx5  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
02dakota                           NaN                   NaN   
02deuce                            NaN               

In [161]:
from sklearn.metrics.pairwise import pairwise_distances

In [162]:
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [163]:
user_correlation[user_correlation<0]=0
user_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [164]:
user_correlation.shape

(18275, 18275)

In [165]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0.        , 0.        , 2.5       , ..., 1.46525748, 1.88982237,
        0.20412415],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [167]:
user_predicted_ratings.shape

(18275, 256)

In [168]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            2.5              3.596262   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   
0325home                           0.0              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                       2.581989              1.018079  ...   
01impala                      0.000000              0.000000  ...   
02dakota                      0.000000              0.000000  ...   
02deuce                       0.000000              0.000000  ...   
0325home                      0.000000              0.000000  ...   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
00sab00                       1.666667              0.188982   
01impala                      0.000000              0.000000   
02dakota                      0.000000              0.000000   
02deuce                       0.000000              0.000000   
0325home                      0.000000              0.000000   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AVpfsQoeilAPnD_xgfx5  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            0.0              1.465257   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0

In [169]:
user_input = '00sab00'

In [170]:
top20_recommendations = user_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
df_top20_recommendations = pd.DataFrame({'Product Id': top20_recommendations.index, 'cosine_similarity_score' : top20_recommendations})
df_top20_recommendations.reset_index(drop=True, inplace=True)
df_top20_recommendations

Product Id  cosine_similarity_score
0   AVpfPaoqLJeJML435Xk9                37.472929
1   AVpfRTh1ilAPnD_xYic2                29.191053
2   AVpf0eb2LJeJML43EVSt                14.259486
3   AVpf3VOfilAPnD_xjpun                12.313738
4   AVpf2tw1ilAPnD_xjflC                11.178377
5   AVpfBrUZilAPnD_xTUly                 7.831663
6   AVpfov9TLJeJML43A7B0                 6.623441
7   AVpf385g1cnluZ0-s0_t                 6.253560
8   AVpfM_ytilAPnD_xXIJb                 6.154565
9   AVpfR5m0LJeJML436K3W                 5.650706
10  AVpfOIrkilAPnD_xXgDG                 5.431250
11  AVpfPnrU1cnluZ0-g9rL                 4.684745
12  AVpf0thK1cnluZ0-r8vR                 3.653338
13  AV1YGDqsGV-KLJ3adc-O                 3.596262
14  AVpfazX31cnluZ0-kbdl                 3.347910
15  AVpfJP1C1cnluZ0-e3Xy                 3.316497
16  AVpe8gsILJeJML43y6Ed                 2.958040
17  AVpfN6Z71cnluZ0-gZmO                 2.926401
18  AVpfMpZ51cnluZ0-f_L9                 2.913289
19  AVpf5Z1zLJeJML43FpB-                 2.886751

In [171]:
top20_rec = pd.merge(df_reco, df_top20_recommendations,left_on='id',right_on='Product Id', how = 'inner')[['Product Id', 'name', 'cosine_similarity_score']].drop_duplicates()
top20_rec.reset_index(drop=True, inplace=True)
top20_rec.sort_values(by='cosine_similarity_score', ascending=False)

Product Id                                               name  \
16  AVpfPaoqLJeJML435Xk9  Godzilla 3d Includes Digital Copy Ultraviolet ...   
19  AVpfRTh1ilAPnD_xYic2  Planes: Fire Rescue (2 Discs) (includes Digita...   
2   AVpf0eb2LJeJML43EVSt     The Resident Evil Collection 5 Discs (blu-Ray)   
6   AVpf3VOfilAPnD_xjpun  Clorox Disinfecting Wipes Value Pack Scented 1...   
4   AVpf2tw1ilAPnD_xjflC                   Red (special Edition) (dvdvideo)   
9   AVpfBrUZilAPnD_xTUly  Coty Airspun Face Powder, Translucent Extra Co...   
15  AVpfov9TLJeJML43A7B0    Bisquick Original Pancake And Baking Mix - 40oz   
5   AVpf385g1cnluZ0-s0_t                             Hormel Chili, No Beans   
11  AVpfM_ytilAPnD_xXIJb                  Tostitos Bite Size Tortilla Chips   
18  AVpfR5m0LJeJML436K3W                     Jason Aldean - They Don't Know   
14  AVpfOIrkilAPnD_xXgDG                              Alex Cross (dvdvideo)   
17  AVpfPnrU1cnluZ0-g9rL  Stargate (ws) (ultimate Edition) (director's C...   
3   AVpf0thK1cnluZ0-r8vR                100:Complete First Season (blu-Ray)   
0   AV1YGDqsGV-KLJ3adc-O  Windex Original Glass Cleaner Refill 67.6oz (2...   
8   AVpfazX31cnluZ0-kbdl  Just For Men Touch Of Gray Gray Hair Treatment...   
10  AVpfJP1C1cnluZ0-e3Xy               Clorox Disinfecting Bathroom Cleaner   
1   AVpe8gsILJeJML43y6Ed  Pendaflex174 Divide It Up File Folder, Multi S...   
13  AVpfN6Z71cnluZ0-gZmO  Caress Moisturizing Body Bar Natural Silk, 4.75oz   
12  AVpfMpZ51cnluZ0-f_L9  Chips Ahoy! Original Chocolate Chip - Cookies ...   
7   AVpf5Z1zLJeJML43FpB-  Lysol Concentrate Deodorizing Cleaner, Origina...   

    cosine_similarity_score  
16                37.472929  
19                29.191053  
2                 14.259486  
6                 12.313738  
4                 11.178377  
9                  7.831663  
15                 6.623441  
5                  6.253560  
11                 6.154565  
18                 5.650706  
14                 5.431250  
17                 4.684745  
3                  3.653338  
0                  3.596262  
8                  3.347910  
10                 3.316497  
1                  2.958040  
13                 2.926401  
12                 2.913289  
7                  2.886751

# Evalution of user user based model

In [172]:
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(2051, 4)

In [173]:
common.head(2)

id  \
12875  AVpf3VOfilAPnD_xjpun   
21657  AVpfm8yiLJeJML43AYyu   

                                                    name  reviews_rating  \
12875  Clorox Disinfecting Wipes Value Pack Scented 1...               5   
21657          Nexxus Exxtra Gel Style Creation Sculptor               1   

      reviews_username  
12875          jessica  
21657       romance318

In [174]:
common_user_based_matrix = common.pivot_table(index='reviews_username', columns='id', values='reviews_rating')

In [175]:
common_user_based_matrix.head(2)

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AV1YneDPglJLPUi8IJyQ  AV1Ys0kTvKc47QAVgx1C  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AV1YtGjdglJLPUi8IOfJ  AV1ZT7GLglJLPUi8IQLI  ...  \
reviews_username                                              ...   
1234                               NaN                   NaN  ...   
1234567                            NaN                   NaN  ...   

id                AVpfov9TLJeJML43A7B0  AVpfpM2yilAPnD_xfmDG  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AVpfrTyiLJeJML43BrSI  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AVpfs0tUilAPnD_xgqN2  AVpfthSailAPnD_xg3ON  \
reviews_username                                               
1234                               NaN                   NaN   
1234567                            NaN                   NaN   

id                AVpftikC1cnluZ0-p31V  AVpfv4TlilAPnD_xhjNS  
reviews_username                                              
1234                               NaN                   NaN  
1234567                            NaN                   NaN  

[2 rows x 140 columns]

In [176]:
user_correlation_df = pd.DataFrame(user_correlation)
user_correlation_df.head(2)

0      1      2      3      4      5      6      7      8      9      ...  \
0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   18265  18266  18267  18268  18269  18270  18271  18272  18273  18274  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[2 rows x 18275 columns]

In [177]:
df_subtracted.head(1)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                            NaN                   NaN  ...   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AVpfsQoeilAPnD_xgfx5  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                            NaN                   NaN   

id                AVpfv4TlilAPnD_xhjNS  AVpfvieo1cnluZ0-qdnu  
reviews_username                                              
00sab00                            NaN                   NaN  

[1 rows x 256 columns]

In [108]:
user_correlation_df['userId'] = df_subtracted.index
user_correlation_df.set_index('userId',inplace=True)
user_correlation_df.head(2)

0      1      2      3      4      5      6      7      8      \
userId                                                                    
00sab00     1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
01impala    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

          9      ...  18265  18266  18267  18268  18269  18270  18271  18272  \
userId           ...                                                           
00sab00     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
01impala    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

          18273  18274  
userId                  
00sab00     0.0    0.0  
01impala    0.0    0.0  

[2 rows x 18275 columns]

In [109]:
common.head(1)

id  \
12875  AVpf3VOfilAPnD_xjpun   

                                                    name  reviews_rating  \
12875  Clorox Disinfecting Wipes Value Pack Scented 1...               5   

      reviews_username  sentiment_score  
12875          jessica             0.85

In [111]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_pivot.index.tolist()
user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]
user_correlation_df_1.shape

(1693, 18275)

In [112]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]
user_correlation_df_3 = user_correlation_df_2.T
user_correlation_df_3.head()

1234  1234567  123charlie  1943  1witch  4 rooms 1 dog lotsa fur  \
userId                                                                         
1234         0.0      0.0         0.0   0.0     0.0                      0.0   
1234567      0.0      0.0         0.0   0.0     0.0                      0.0   
123charlie   0.0      0.0         0.0   0.0     0.0                      0.0   
1943         0.0      0.0         0.0   0.0     0.0                      0.0   
1witch       0.0      0.0         0.0   0.0     0.0                      0.0   

            85lisa  a hutch  aac06002  aalyah  ...  xavier  yamel97  \
userId                                         ...                    
1234           0.0      0.0       0.0     0.0  ...     0.0      0.0   
1234567        0.0      0.0       0.0     0.0  ...     0.0      0.0   
123charlie     0.0      0.0       0.0     0.0  ...     0.0      0.0   
1943           0.0      0.0       0.0     0.0  ...     0.0      0.0   
1witch         0.0      0.0       0.0     0.0  ...     0.0      0.0   

            yayawomack  yorkielvr  yummy  yvonne  zach  zebras  zippy  zxcsdfd  
userId                                                                          
1234               0.0        0.0    0.0     0.0   0.0     0.0    0.0      0.0  
1234567            0.0        0.0    0.0     0.0   0.0     0.0    0.0      0.0  
123charlie         0.0        0.0    0.0     0.0   0.0     0.0    0.0      0.0  
1943               0.0        0.0    0.0     0.0   0.0     0.0    0.0      0.0  
1witch             0.0        0.0    0.0     0.0   0.0     0.0    0.0      0.0  

[5 rows x 1693 columns]

In [113]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [114]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='id', values='reviews_rating').fillna(0)

In [115]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [116]:
common_user_predicted_ratings.head(2)

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AV1YneDPglJLPUi8IJyQ  AV1Ys0kTvKc47QAVgx1C  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AV1YtGjdglJLPUi8IOfJ  AV1ZT7GLglJLPUi8IQLI  ...  \
reviews_username                                              ...   
1234                               0.0                   0.0  ...   
1234567                            0.0                   0.0  ...   

id                AVpfov9TLJeJML43A7B0  AVpfpM2yilAPnD_xfmDG  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AVpfrTyiLJeJML43BrSI  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AVpfs0tUilAPnD_xgqN2  AVpfthSailAPnD_xg3ON  \
reviews_username                                               
1234                               0.0                   0.0   
1234567                            0.0                   0.0   

id                AVpftikC1cnluZ0-p31V  AVpfv4TlilAPnD_xhjNS  
reviews_username                                              
1234                               0.0                   0.0  
1234567                            0.0                   0.0  

[2 rows x 140 columns]

In [117]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


C:\Users\Chilkaditya Das\anaconda3\lib\site-packages\sklearn\preprocessing\_data.py:461: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
C:\Users\Chilkaditya Das\anaconda3\lib\site-packages\sklearn\preprocessing\_data.py:462: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [118]:
common_ = common.pivot_table(index='reviews_username', columns='id', values='reviews_rating')

In [119]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [120]:
rmse_user_user = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse_user_user)

2.551419404666111


# item-item based

In [178]:
df_pivot = train.pivot_table(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).T

In [179]:
df_pivot.head()

reviews_username      00sab00  01impala  02dakota  02deuce  0325home  \
id                                                                     
AV13O1A8GV-KLJ3akUyj      NaN       NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS      NaN       NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn      NaN       NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O      NaN       NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG      NaN       NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  1085  ...  \
id                                                                      ...   
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN   NaN  ...   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN   NaN  ...   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN   NaN  ...   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN   NaN  ...   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN   NaN  ...   

reviews_username      zsarah  zsazsa  zubb  zuttle  zwithanx  zxcsdfd  zxjki  \
id                                                                             
AV13O1A8GV-KLJ3akUyj     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV14LG0R-jtxr-f38QfS     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV16khLE-jtxr-f38VFn     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV1YGDqsGV-KLJ3adc-O     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV1YIch7GV-KLJ3addeG     NaN     NaN   NaN     NaN       NaN      NaN    NaN   

reviews_username      zyiah4  zzdiane  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj     NaN      NaN      NaN  
AV14LG0R-jtxr-f38QfS     NaN      NaN      NaN  
AV16khLE-jtxr-f38VFn     NaN      NaN      NaN  
AV1YGDqsGV-KLJ3adc-O     NaN      NaN      NaN  
AV1YIch7GV-KLJ3addeG     NaN      NaN      NaN  

[5 rows x 18275 columns]

In [180]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [181]:
df_subtracted.head()

reviews_username      00sab00  01impala  02dakota  02deuce  0325home  \
id                                                                     
AV13O1A8GV-KLJ3akUyj      NaN       NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS      NaN       NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn      NaN       NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O      NaN       NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG      NaN       NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  1085  ...  \
id                                                                      ...   
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN   NaN  ...   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN   NaN  ...   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN   NaN  ...   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN   NaN  ...   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN   NaN  ...   

reviews_username      zsarah  zsazsa  zubb  zuttle  zwithanx  zxcsdfd  zxjki  \
id                                                                             
AV13O1A8GV-KLJ3akUyj     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV14LG0R-jtxr-f38QfS     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV16khLE-jtxr-f38VFn     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV1YGDqsGV-KLJ3adc-O     NaN     NaN   NaN     NaN       NaN      NaN    NaN   
AV1YIch7GV-KLJ3addeG     NaN     NaN   NaN     NaN       NaN      NaN    NaN   

reviews_username      zyiah4  zzdiane  zzz1127  
id                                              
AV13O1A8GV-KLJ3akUyj     NaN      NaN      NaN  
AV14LG0R-jtxr-f38QfS     NaN      NaN      NaN  
AV16khLE-jtxr-f38VFn     NaN      NaN      NaN  
AV1YGDqsGV-KLJ3adc-O     NaN      NaN      NaN  
AV1YIch7GV-KLJ3addeG     NaN      NaN      NaN  

[5 rows x 18275 columns]

In [182]:
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [183]:
item_correlation[item_correlation<0]=0
item_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [184]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.00603917, 0.06485571,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.0094556 ],
       [0.        , 0.        , 0.        , ..., 0.00781596, 0.10809285,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00756448]])

In [185]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00sab00                            0.0              0.006042   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   
0325home                           0.0              0.000082   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00sab00                            0.0              0.000000   
01impala                           0.0              0.000000   
02dakota                           0.0              0.000000   
02deuce                            0.0              0.000000   
0325home                           0.0              0.001244   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
00sab00                       0.000000              0.000000  ...   
01impala                      0.000000              0.000000  ...   
02dakota                      0.000000              0.000000  ...   
02deuce                       0.000000              0.000000  ...   
0325home                      0.002197              0.001808  ...   

id                AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
reviews_username                                               
00sab00                            0.0              0.000000   
01impala                           0.0              0.097645   
02dakota                           0.0              0.162741   
02deuce                            0.0              0.130193   
0325home                           0.0              0.000000   

id                AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AVpfsQoeilAPnD_xgfx5  AVpfshNsLJeJML43CB8q  \
reviews_username                                               
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02dakota                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
00sab00                       0.020509              0.006039   
01impala                      0.000000              0.000000   
02dakota                      0.000000              0.000000   
02deuce                       0.000000              0

In [186]:
user_input = '00sab00'

In [187]:
top20_item_recommendations = item_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
df_top20_item_recommendations = pd.DataFrame({'Product Id': top20_item_recommendations.index, 'cosine_similarity_score' : top20_item_recommendations})
df_top20_item_recommendations.reset_index(drop=True, inplace=True)
df_top20_item_recommendations

Product Id  cosine_similarity_score
0   AVpfE7puilAPnD_xUcCW                 0.147125
1   AVpfv4TlilAPnD_xhjNS                 0.064856
2   AVpfJcHuLJeJML433ZrY                 0.052161
3   AVpf0thK1cnluZ0-r8vR                 0.036554
4   AVpe6PCDLJeJML43yFQH                 0.032108
5   AVpe_dxlilAPnD_xSiHI                 0.030764
6   AVpfQtEm1cnluZ0-hUpe                 0.027387
7   AVpfHf4wLJeJML432vqK                 0.022930
8   AVpfthSailAPnD_xg3ON                 0.020509
9   AVpe6FfKilAPnD_xQmHi                 0.020308
10  AVpe_pDG1cnluZ0-bjSf                 0.017473
11  AVpf5CnILJeJML43FjaU                 0.016342
12  AVpe4pnBilAPnD_xQDeb                 0.016089
13  AVpe6n2_LJeJML43yOgE                 0.016038
14  AVpfoSS51cnluZ0-oVH9                 0.015625
15  AVpfOmKwLJeJML435GM7                 0.015489
16  AVpfbraG1cnluZ0-kqnn                 0.014867
17  AVpfOIrkilAPnD_xXgDG                 0.014704
18  AVpe8gsILJeJML43y6Ed                 0.014632
19  AVpe31o71cnluZ0-YrSD                 0.014597

In [188]:
top20_item_rec = pd.merge(df_reco, df_top20_item_recommendations,left_on='id',right_on='Product Id', how = 'inner')[['Product Id', 'name', 'cosine_similarity_score']].drop_duplicates()
top20_item_rec.reset_index(drop=True, inplace=True)
top20_item_rec.sort_values(by='cosine_similarity_score', ascending=False)

Product Id                                               name  \
11  AVpfE7puilAPnD_xUcCW           Bilbao Nightstand Gray Oak - South Shore   
19  AVpfv4TlilAPnD_xhjNS  Various - Red Hot Blue:Tribute To Cole Porter ...   
13  AVpfJcHuLJeJML433ZrY                                   Equals (blu-Ray)   
8   AVpf0thK1cnluZ0-r8vR                100:Complete First Season (blu-Ray)   
6   AVpe6PCDLJeJML43yFQH             Wagan Smartac 80watt Inverter With Usb   
0   AVpe_dxlilAPnD_xSiHI  The Seaweed Bath Co. Argan Conditioner, Smooth...   
17  AVpfQtEm1cnluZ0-hUpe          Jolly Time Select Premium Yellow Pop Corn   
12  AVpfHf4wLJeJML432vqK             Trend Lab Park Nursing Cover - Paisley   
18  AVpfthSailAPnD_xg3ON              Musselman Apple Sauce, Cinnamon, 48oz   
4   AVpe6FfKilAPnD_xQmHi       Chex Muddy Buddies Brownie Supreme Snack Mix   
1   AVpe_pDG1cnluZ0-bjSf        Bi-O-kleen Spray & Wipe All Purpose Cleaner   
9   AVpf5CnILJeJML43FjaU  WeatherTech 40647 14-15 Outlander Cargo Liners...   
3   AVpe4pnBilAPnD_xQDeb    Moom Express Pre Waxed Strips For Face & Bikini   
5   AVpe6n2_LJeJML43yOgE     Tresemme Kertatin Smooth Infusing Conditioning   
16  AVpfoSS51cnluZ0-oVH9  Cheetos Crunchy Flamin' Hot Cheese Flavored Sn...   
15  AVpfOmKwLJeJML435GM7  Clear Scalp & Hair Therapy Total Care Nourishi...   
10  AVpfbraG1cnluZ0-kqnn                               Kind Nut Delight Bar   
14  AVpfOIrkilAPnD_xXgDG                              Alex Cross (dvdvideo)   
7   AVpe8gsILJeJML43y6Ed  Pendaflex174 Divide It Up File Folder, Multi S...   
2   AVpe31o71cnluZ0-YrSD  Dark Shadows (includes Digital Copy) (ultravio...   

    cosine_similarity_score  
11                 0.147125  
19                 0.064856  
13                 0.052161  
8                  0.036554  
6                  0.032108  
0                  0.030764  
17                 0.027387  
12                 0.022930  
18                 0.020509  
4                  0.020308  
1                  0.017473  
9                  0.016342  
3                  0.016089  
5                  0.016038  
16                 0.015625  
15                 0.015489  
10                 0.014867  
14                 0.014704  
7                  0.014632  
2                  0.014597

# Evalution item-item

In [189]:
test.columns

Index(['id', 'name', 'reviews_rating', 'reviews_username'], dtype='object')

In [190]:
common = test[test.id.isin(train.id)]
common.shape

(8966, 4)

In [191]:
common.head(2)

id  \
25787  AVpfPaoqLJeJML435Xk9   
12627  AVpf3VOfilAPnD_xjpun   

                                                    name  reviews_rating  \
25787  Godzilla 3d Includes Digital Copy Ultraviolet ...               5   
12627  Clorox Disinfecting Wipes Value Pack Scented 1...               5   

       reviews_username  
25787  youknowhowitgoes  
12627      ashleydale00

In [192]:
common_item_based_matrix = common.pivot_table(index='reviews_username', columns='id', values='reviews_rating').T

In [193]:
common_item_based_matrix.shape

(195, 8318)

In [194]:
item_correlation_df = pd.DataFrame(item_correlation)

In [195]:
item_correlation_df.head(2)

0    1    2    3    4    5    6    7    8    9    ...  246  247  248  249  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   250  251  252  253  254  255  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  

[2 rows x 256 columns]

In [196]:
item_correlation_df['movieId'] = df_subtracted.index
item_correlation_df.set_index('movieId',inplace=True)
item_correlation_df.head()

0    1    2    3    4    5    6    7    8    9    ...  \
movieId                                                                 ...   
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV16khLE-jtxr-f38VFn  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   

                      246  247  248  249  250  251  252  253  254  255  
movieId                                                                 
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
AV16khLE-jtxr-f38VFn  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 256 columns]

In [197]:
list_name = common.id.tolist()

In [198]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [199]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [200]:
item_correlation_df_3.head(2)

AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   1.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   1.0   

                      AV1YlENIglJLPUi8IHsX  AV1YmBrdGV-KLJ3adewb  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   

                      AV1YmDL9vKc47QAVgr7_  AV1Ymf_rglJLPUi8II2v  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   

                      AV1Yn94nvKc47QAVgtst  AV1Ynb3bglJLPUi8IJxJ  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   

                      AV1YneDPglJLPUi8IJyQ  AV1YqAaMGV-KLJ3adiDj  ...  \
movieId                                                           ...   
AV16khLE-jtxr-f38VFn                   0.0                   0.0  ...   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0  ...   

                      AVpfqW4WilAPnD_xf7a_  AVpfr5cb1cnluZ0-pZFp  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   0.0              0.000000   
AV1YGDqsGV-KLJ3adc-O                   0.0              0.108098   

                      AVpfrFDZLJeJML43Bmv0  AVpfrTyiLJeJML43BrSI  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   

                      AVpfrfHF1cnluZ0-pRai  AVpfrgjFLJeJML43BvCc  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   

                      AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
movieId                                                            
AV16khLE-jtxr-f38VFn                   0.0                   0.0   
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0   

                      AVpfv4TlilAPnD_xhjNS  AVpfvieo1cnluZ0-qdnu  
movieId                                                           
AV16khLE-jtxr-f38VFn                   0.0                   0.0  
AV1YGDqsGV-KLJ3adc-O                   0.0                   0.0  

[2 rows x 195 columns]

In [201]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.34691174e-02, 3.00000000e+00, 6.62104097e-03, ...,
        0.00000000e+00, 5.16904870e-03, 8.22214474e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 9.45559849e-03]])

In [202]:
common_item_predicted_ratings.shape

(195, 8318)

In [203]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='id', values='reviews_rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

In [204]:
common_ = common.pivot_table(index='reviews_username', columns='id', values='reviews_rating').T

In [205]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

C:\Users\Chilkaditya Das\anaconda3\lib\site-packages\sklearn\preprocessing\_data.py:461: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
C:\Users\Chilkaditya Das\anaconda3\lib\site-packages\sklearn\preprocessing\_data.py:462: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan  1. nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [206]:
total_non_nan = np.count_nonzero(~np.isnan(y))

In [207]:
rmse_item_item = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse_item_item)

3.5442022225107723


# Best-suited Recommendation model

In [208]:
if rmse_user_user < rmse_item_item:
  print("Best-fit model is user-user recommendation system")
else:
  print("Best-fit model is item-item recommendation system")

Best-fit model is user-user recommendation system


In [209]:
user_input = 'evrydayhustla420'

In [210]:
top20_recommendations = user_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
df_top20_recommendations = pd.DataFrame({'Product Id': top20_recommendations.index, 'cosine_similarity_score' : top20_recommendations})
df_top20_recommendations.reset_index(drop=True, inplace=True)
df_top20_recommendations

Product Id  cosine_similarity_score
0   AVpfRTh1ilAPnD_xYic2                16.870920
1   AVpe41TqilAPnD_xQH3d                13.017496
2   AVpf0eb2LJeJML43EVSt                11.843501
3   AVpf3VOfilAPnD_xjpun                 9.609059
4   AVpe59io1cnluZ0-ZgDU                 7.706569
5   AVpfJP1C1cnluZ0-e3Xy                 5.474655
6   AVpfOIrkilAPnD_xXgDG                 4.809401
7   AVpfPnrU1cnluZ0-g9rL                 4.539020
8   AVpe31o71cnluZ0-YrSD                 4.336229
9   AVpe8gsILJeJML43y6Ed                 4.309060
10  AVpf5olc1cnluZ0-tPrO                 3.909127
11  AVpe9W4D1cnluZ0-avf0                 3.147079
12  AVpfM_ytilAPnD_xXIJb                 3.051318
13  AVpfN6Z71cnluZ0-gZmO                 2.500000
14  AVpfIOoV1cnluZ0-ehGp                 2.500000
15  AVpfazX31cnluZ0-kbdl                 2.269582
16  AVpfOmKwLJeJML435GM7                 2.237478
17  AVpf385g1cnluZ0-s0_t                 2.120199
18  AVpf0thK1cnluZ0-r8vR                 2.120089
19  AVpfUJu_ilAPnD_xZdDr                 2.000000

In [211]:
top20_rec = pd.merge(df_reco, df_top20_recommendations,left_on='id',right_on='Product Id', how = 'inner')[['Product Id', 'name', 'cosine_similarity_score']].drop_duplicates()
top20_rec.reset_index(drop=True, inplace=True)
top20_rec.sort_values(by='cosine_similarity_score', ascending=False)

Product Id                                               name  \
18  AVpfRTh1ilAPnD_xYic2  Planes: Fire Rescue (2 Discs) (includes Digita...   
1   AVpe41TqilAPnD_xQH3d       Mike Dave Need Wedding Dates (dvd + Digital)   
5   AVpf0eb2LJeJML43EVSt     The Resident Evil Collection 5 Discs (blu-Ray)   
8   AVpf3VOfilAPnD_xjpun  Clorox Disinfecting Wipes Value Pack Scented 1...   
2   AVpe59io1cnluZ0-ZgDU  My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Di...   
12  AVpfJP1C1cnluZ0-e3Xy               Clorox Disinfecting Bathroom Cleaner   
15  AVpfOIrkilAPnD_xXgDG                              Alex Cross (dvdvideo)   
17  AVpfPnrU1cnluZ0-g9rL  Stargate (ws) (ultimate Edition) (director's C...   
0   AVpe31o71cnluZ0-YrSD  Dark Shadows (includes Digital Copy) (ultravio...   
3   AVpe8gsILJeJML43y6Ed  Pendaflex174 Divide It Up File Folder, Multi S...   
9   AVpf5olc1cnluZ0-tPrO          Chester's Cheese Flavored Puffcorn Snacks   
4   AVpe9W4D1cnluZ0-avf0  Hoover174 Platinum Collection153 Lightweight B...   
13  AVpfM_ytilAPnD_xXIJb                  Tostitos Bite Size Tortilla Chips   
11  AVpfIOoV1cnluZ0-ehGp  Reebok Classic Leather Running Shoes - White (...   
14  AVpfN6Z71cnluZ0-gZmO  Caress Moisturizing Body Bar Natural Silk, 4.75oz   
10  AVpfazX31cnluZ0-kbdl  Just For Men Touch Of Gray Gray Hair Treatment...   
16  AVpfOmKwLJeJML435GM7  Clear Scalp & Hair Therapy Total Care Nourishi...   
7   AVpf385g1cnluZ0-s0_t                             Hormel Chili, No Beans   
6   AVpf0thK1cnluZ0-r8vR                100:Complete First Season (blu-Ray)   
19  AVpfUJu_ilAPnD_xZdDr  Chobani174 Strawberry On The Bottom Non-Fat Gr...   

    cosine_similarity_score  
18                16.870920  
1                 13.017496  
5                 11.843501  
8                  9.609059  
2                  7.706569  
12                 5.474655  
15                 4.809401  
17                 4.539020  
0                  4.336229  
3                  4.309060  
9                  3.909127  
4                  3.147079  
13                 3.051318  
11                 2.500000  
14                 2.500000  
10                 2.269582  
16                 2.237478  
7                  2.120199  
6                  2.120089  
19                 2.000000